[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "spyglass-neuro"
description = "Neuroscience data analysis framework for reproducible research"
readme = "README.md"
requires-python = ">=3.9,<3.10"
license = { file = "LICENSE" }
authors = [
    { name = "Loren Frank", email = "loren.frank@ucsf.edu" },
    { name = "Kyu Hyun Lee", email = "kyuhyun.lee@ucsf.edu" },
    { name = "Eric Denovellis", email = "eric.denovellis@ucsf.edu" },
    { name = "Ryan Ly", email = "rly@lbl.gov" },
    { name = "Daniel Gramling", email = "daniel.gramling@ucsf.edu" },
    { name = "Chris Brozdowski", email = "chris.broz@ucsf.edu" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = [
    "neuroscience",
    "research",
    "electrophysiology",
    "reproducible",
    "data analysis",
    "spike sorting",
    "spikeinterface",
    "datajoint",
    "nwb",
    "kachery",
    "sortingview",
]
dependencies = [
    "pydotplus",
    "dask",
    "position_tools",
    "track_linearization>=2.3",
    "replay_trajectory_classification",
    "ripple_detection",
    "trajectory_analysis_tools",
    "matplotlib",
    "seaborn",
    "bottleneck",
    "numpy<1.24",
    "ipympl",
    "tqdm",
    "pubnub<6.4.0",
    "pynwb>=2.2.0,<3",
    "hdmf>=3.4.6",
    "datajoint>=0.13.6",
    "pymysql",
    "sortingview>=0.11",
    "pyyaml",
    "click",
    "spikeinterface",
    "ndx_franklab_novela>=0.1.0",
]
dynamic = ["version"]

[project.scripts]
spyglass_cli = "spyglass.cli:cli"

[project.urls]
"Homepage" = "https://github.com/LorenFrankLab/spyglass"
"Bug Tracker" = "https://github.com/LorenFrankLab/spyglass/issues"

[project.optional-dependencies]
position = ["ffmpeg", "numba>=0.54", "deeplabcut<2.3.0"]
test = [
    "pytest",         # unit testing
    "pytest-cov",     # code coverage
    "kachery",        # database access
    "kachery-client",
    "kachery-cloud",
]
docs = [
    "hatch",                 # Get version from env
    "mike",                  # Docs versioning
    "mkdocs",                # Docs core
    "mkdocs-exclude",        # Docs exclude files
    "mkdocs-exclude-search", # Docs exclude files in search
    "mkdocs-gen-files",      # Docs API generator
    "mkdocs-jupyter",        # Docs render notebooks
    "mkdocs-literate-nav",   # Dynamic page list for API docs
    "mkdocs-material",       # Docs theme
    "mkdocstrings[python]",  # Docs API docstrings
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
# this file is created/updated when the package is installed and used in
# src/spyglass/__init__.py to set `spyglass.__version__`
version-file = "src/spyglass/_version.py"

[tool.hatch.build.targets.sdist]
exclude = [".git_archival.txt"]

[tool.hatch.build.targets.wheel]
packages = ["src/spyglass"]
exclude = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 80

[tool.codespell]
skip = '.git,*.pdf,*.svg,*.ipynb,./docs/site/**'
# Nevers - name in Citation
ignore-words-list = 'nevers'

[tool.ruff]
src = ["src"]
select = [
    # "C90", # Complexity
    "D", # Docstrings  
    "F", # Pyflakes
    "E", # Pycodestyle
    "W", # Pycodestyle
    "I001" # isort
]
line-length = 80
target-version = "py38"
ignore = [
  "F401", # Unused imports
  "D100", # Module-level docstrings
] 

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"cli.py" = ["D103"]

[tool.pytest.ini_options]
minversion = "6.2"
addopts = "--cov=spyglass --cov-report term-missing"
testpaths =  "tests"

[tool.coverage.run]
omit = [ # Omitting items with no coverage
  "**/temp*py",
  "*/cli/*",
  "*/decoding/*",
  "*/figurl_views/*",
  "*/position/*",
  "*/sharing/*",
  "*/spikesorting/*",
  "*/lfp/*",
  "*/lfp_band/*",
  "*/common/*",
  "*/utils/*",
] 
